-- Auto-generated by parse_and_generate_sql.py
-- Real Uber Eats prices for ALL 375 items across 42 sections
-- Run: mysql -u root qfood < spiros_updates.sql

USE qfood;


-- ══ Pancakes ══
UPDATE food SET food_price = 13.5, food_src = 'https://d1ralsognjng37.cloudfront.net/38942f06-099e-4e21-9cce-ab61546a0a79.jpeg', food_desc = 'Pancakes, 2 eggs, ham, bacon and sausage.', food_star = 4.9 WHERE food_name = 'Lumber Jack' AND food_category = 'pancakes';
UPDATE food SET food_price = 13.5, food_src = 'https://tb-static.uber.com/prod/image-proc/processed_images/fedd453cba1c270b8c9b52b74d6474f5/3093d07d5a810674a6d7adf26679874b.jpeg', food_desc = 'French toast, 2 eggs, ham, bacon and sausage.', food_star = 4.8 WHERE food_name = 'He Man' AND food_category = 'pancakes';
UPDATE food SET food_price = 9.75, food_desc = 'Fluffy and soft breakfast treat.' WHERE food_name = 'Pancakes' AND food_category = 'pancakes';
UPDATE food SET food_price = 13.5, food_desc = '1 pancake, 1 French toast, 2 eggs, ham, bacon and sausage.' WHERE food_name = 'Super Man' AND food_category = 'pancakes';
UPDATE food SET food_price = 10.25, food_desc = 'Fluffy, sweet pancakes served hot.' WHERE food_name = 'Silver Dollar Pancakes' AND food_category = 'pancakes';

-- ══ French Toast and Waffles ══
UPDATE food SET food_price = 9.75, food_src = 'https://d1ralsognjng37.cloudfront.net/b8198c58-d778-40e2-ae44-26de8dd4859f.jpeg', food_desc = 'Light and crispy breakfast treat.' WHERE food_name = 'Waffle' AND food_category = 'french-toast-waffles';
UPDATE food SET food_price = 9.75, food_src = 'https://d1ralsognjng37.cloudfront.net/006c69cd-3300-47de-b98c-1f0458923a42.jpeg', food_desc = 'Thick slices of bread dipped in egg and grilled to a golden brown.' WHERE food_name = 'French Toast' AND food_category = 'french-toast-waffles';
UPDATE food SET food_price = 10.25, food_desc = 'Rich, sweet bread dipped in egg batter and grilled to a golden brown.' WHERE food_name = 'Challah French Toast' AND food_category = 'french-toast-waffles';
UPDATE food SET food_price = 14.5, food_desc = 'Includes bacon, ham and sausage.', food_star = 4.8 WHERE food_name = 'Waffle Deluxe' AND food_category = 'french-toast-waffles';
UPDATE food SET food_price = 16.75, food_desc = 'Crispy waffle served with three tender chicken fingers.' WHERE food_name = 'Waffle with 3 chicken fingers' AND food_category = 'french-toast-waffles';
UPDATE food SET food_price = 14.75, food_desc = 'Crisp waffle served with a scoop of creamy ice cream.' WHERE food_name = 'Waffle with Ice Cream' AND food_category = 'french-toast-waffles';

-- ══ Eggs and 3 Egg Omelettes ══
UPDATE food SET food_price = 14.75, food_src = 'https://d1ralsognjng37.cloudfront.net/af7b6afa-264e-42ea-9bb8-3c7dfbcbc5e4.jpeg', food_desc = 'Fresh eggs blended with garden vegetables, served in a fluffy omelette.', food_star = 4.8 WHERE food_name = '3 Eggs Garden Omelette' AND food_category = 'eggs-omelettes';
UPDATE food SET food_price = 9.25, food_desc = 'Two eggs, cooked to your liking.' WHERE food_name = '2 Eggs Any Style' AND food_category = 'eggs-omelettes';
UPDATE food SET food_price = 13.25, food_desc = 'Tender corned beef and eggs, a classic breakfast combination.' WHERE food_name = 'Corned Beef Hash and Eggs' AND food_category = 'eggs-omelettes';
UPDATE food SET food_price = 15.25, food_desc = '3 eggs any style with bacon, ham or sausage and cheese. All egg dishes served with potatoes and toast. No substitutes. Add cheese for an additional charge. Substitute sweet potato fries or onion rings for an additional charge.' WHERE food_name = 'House 3 Egg Special' AND food_category = 'eggs-omelettes';
UPDATE food SET food_price = 13.25, food_desc = 'Fluffy eggs with a savory twist.' WHERE food_name = 'Western Omelette' AND food_category = 'eggs-omelettes';
UPDATE food SET food_price = 13.95, food_desc = 'Fluffy eggs wrapped with crispy bacon.' WHERE food_name = 'Bacon Omelette' AND food_category = 'eggs-omelettes';
UPDATE food SET food_price = 13.0, food_desc = 'Fluffy eggs blended with melted cheese.', food_star = 4.8 WHERE food_name = 'Cheese Omelette' AND food_category = 'eggs-omelettes';
UPDATE food SET food_price = 24.95, food_desc = 'Tender steak paired with eggs.' WHERE food_name = 'Roumanian Steak and Eggs' AND food_category = 'eggs-omelettes';
UPDATE food SET food_price = 13.0, food_desc = 'Fresh avocado wrapped in a fluffy omelette.' WHERE food_name = 'Avocado Omelette' AND food_category = 'eggs-omelettes';
UPDATE food SET food_price = 13.95, food_desc = 'Fluffy eggs filled with savory ham.' WHERE food_name = 'Ham Omelette' AND food_category = 'eggs-omelettes';
UPDATE food SET food_price = 14.75, food_desc = 'Tender corned beef and eggs blended in a fluffy omelette.' WHERE food_name = 'Corned Beef Hash Omelette' AND food_category = 'eggs-omelettes';
UPDATE food SET food_price = 15.0, food_desc = 'Flavorful omelette filled with sautéed onions, peppers, and melted cheese.' WHERE food_name = 'Onion, Pepper and Cheese Omelette' AND food_category = 'eggs-omelettes';
UPDATE food SET food_price = 22.95, food_desc = 'Thick-cut Virginia ham served with eggs.' WHERE food_name = 'Virginia Ham Steak and Eggs' AND food_category = 'eggs-omelettes';
UPDATE food SET food_price = 13.0, food_desc = 'Fluffy eggs with broccoli.' WHERE food_name = 'Broccoli Omelette' AND food_category = 'eggs-omelettes';
UPDATE food SET food_price = 13.0, food_desc = 'Fresh spinach wrapped in a fluffy egg omelette.' WHERE food_name = 'Spinach Omelette' AND food_category = 'eggs-omelettes';
UPDATE food SET food_price = 14.75, food_desc = 'Tender corned beef wrapped in a fluffy omelette.' WHERE food_name = 'Corned Beef Omelette' AND food_category = 'eggs-omelettes';
UPDATE food SET food_price = 13.0, food_desc = 'Fluffy eggs filled with sautéed mushrooms.' WHERE food_name = 'Mushroom Omelette' AND food_category = 'eggs-omelettes';
UPDATE food SET food_price = 14.75, food_desc = 'Fluffy eggs with turkey.' WHERE food_name = 'Turkey Omelette' AND food_category = 'eggs-omelettes';
UPDATE food SET food_price = 14.75, food_desc = 'Fresh tomatoes and melted cheese blended together in a fluffy omelette.' WHERE food_name = 'Tomatoes and Cheese Omelette' AND food_category = 'eggs-omelettes';
UPDATE food SET food_price = 10.75, food_desc = 'Fluffy eggs, expertly cooked to your liking.' WHERE food_name = '3 Egg Omelette' AND food_category = 'eggs-omelettes';
UPDATE food SET food_price = 13.0, food_desc = 'Flavorful omelette filled with sautéed onions and peppers.' WHERE food_name = 'Onion and Pepper Omelette' AND food_category = 'eggs-omelettes';
UPDATE food SET food_price = 13.75, food_desc = 'Fluffy eggs blended with crumbled feta cheese.' WHERE food_name = 'Feta Cheese Omelette' AND food_category = 'eggs-omelettes';
UPDATE food SET food_price = 13.0, food_desc = 'Spicy omelette filled with jalapeno peppers.' WHERE food_name = 'Jalapeno Omelette' AND food_category = 'eggs-omelettes';
UPDATE food SET food_price = 14.75, food_desc = 'Thinly sliced pastrami wrapped in a fluffy omelette.' WHERE food_name = 'Pastrami Omelette' AND food_category = 'eggs-omelettes';
UPDATE food SET food_price = 13.0, food_desc = 'Flavorful eggs with a Spanish twist.' WHERE food_name = 'Spanish Omelette' AND food_category = 'eggs-omelettes';
UPDATE food SET food_price = 15.0, food_desc = 'Smoked salmon and sautéed onions wrapped in a fluffy omelette.' WHERE food_name = 'Lox and Onion Omelette' AND food_category = 'eggs-omelettes';
UPDATE food SET food_price = 1.75, food_desc = 'Crispy waffle-cut fries served as a side.' WHERE food_name = 'Add waffle fries 1.50' AND food_category = 'eggs-omelettes';

-- ══ Omelettes ══
UPDATE food SET food_price = 15.95, food_desc = 'Western eggs, bacon, cheddar, mozzarella and home fries.' WHERE food_name = 'Big Mess Omelette' AND food_category = 'omelettes';
UPDATE food SET food_price = 15.75, food_desc = 'Bacon, ham, sausage, onions and cheese.' WHERE food_name = 'Super Brooklyn 3 Egg Special Omelette' AND food_category = 'omelettes';
UPDATE food SET food_price = 14.75, food_desc = 'Fresh tomatoes, peppers, onions, mushrooms and feta cheese.' WHERE food_name = 'Mediterranean 3 Egg Omelette' AND food_category = 'omelettes';
UPDATE food SET food_price = 14.95, food_desc = 'Fresh avocado, onions, and jalapeno peppers blended in a fluffy omelette.' WHERE food_name = '3. Avocado, Onions and Jalapeno Peppers Omelette' AND food_category = 'omelettes';
UPDATE food SET food_price = 15.0, food_desc = 'Swiss cheese, bacon, onion and mushrooms.' WHERE food_name = 'Spiro\'s Super 3 Egg Omelette' AND food_category = 'omelettes';
UPDATE food SET food_price = 14.75, food_desc = 'Scrambled style.' WHERE food_name = '3 Eggs and Mixed Cheese Omelette' AND food_category = 'omelettes';
UPDATE food SET food_price = 14.75, food_desc = 'Nathan\'s hot dog and cheddar cheese.' WHERE food_name = 'Coney Omelette' AND food_category = 'omelettes';
UPDATE food SET food_price = 15.75, food_desc = 'Avocado, spinach and Swiss.' WHERE food_name = '4. Chef\'s Omelette' AND food_category = 'omelettes';
UPDATE food SET food_price = 15.0, food_desc = 'Mozzarella cheese, onions, tomatoes and peppers.' WHERE food_name = 'Avenue U 3 Egg Omelette' AND food_category = 'omelettes';
UPDATE food SET food_price = 14.95, food_desc = 'Fresh avocado, tomato, and mushrooms blended in a fluffy omelette.' WHERE food_name = '1. Avocado, Tomato and Mushrooms Omelette' AND food_category = 'omelettes';
UPDATE food SET food_price = 15.75, food_desc = 'Fresh avocado, turkey breast, and Swiss cheese blended in a fluffy omelette.' WHERE food_name = '2. Avocado, Turkey Breast and Swiss Omelette' AND food_category = 'omelettes';
UPDATE food SET food_price = 14.95, food_desc = 'Spinach and feta cheese.' WHERE food_name = 'Florentine Omelette' AND food_category = 'omelettes';
UPDATE food SET food_price = 14.95, food_desc = 'Served with feta cheese and tomato.' WHERE food_name = 'Greek Omelette' AND food_category = 'omelettes';
UPDATE food SET food_price = 14.75, food_desc = 'Mozzarella cheese and marinara sauce.' WHERE food_name = 'Italian Omelette' AND food_category = 'omelettes';

-- ══ Spiro's Special ══
UPDATE food SET food_price = 16.25, food_src = 'https://tb-static.uber.com/prod/image-proc/processed_images/7506c43c9f55eb5b27790463e7c0ce31/3093d07d5a810674a6d7adf26679874b.jpeg', food_desc = 'Served with home fries and toast.', food_star = 5.0 WHERE food_name = '2 Eggs with 2 Meats' AND food_category = 'spiros-special';

-- ══ Low Cal Omelettes ══
UPDATE food SET food_price = 14.95, food_desc = 'Served with broccoli, mushroom and tomato. Made with 4 egg whites. Served with lettuce and tomato or potatoes. Add cheese for an additional charge.', food_star = 4.8 WHERE food_name = 'Vegetable Omelette' AND food_category = 'low-cal-omelettes';
UPDATE food SET food_price = 14.95, food_desc = 'Fresh mushrooms and spinach blended in a fluffy omelette.' WHERE food_name = 'Mushroom and Spinach Omelette' AND food_category = 'low-cal-omelettes';
UPDATE food SET food_price = 15.0, food_desc = 'Made with 4 egg whites. Served with lettuce and tomato or potatoes. Add cheese for an additional charge. Made with 4 egg whites. Served with lettuce and tomato or potatoes. Add cheese for an additional charge.' WHERE food_name = 'Turkey Omelette' AND food_category = 'low-cal-omelettes';
UPDATE food SET food_price = 14.95, food_desc = 'A delicate blend of cottage cheese in a fluffy omelette.' WHERE food_name = 'Cottage Cheese Omelette' AND food_category = 'low-cal-omelettes';

-- ══ Super 3 Egg Omelette Wrap ══
UPDATE food SET food_price = 13.95, food_desc = 'Mozzarella and cheese. All wraps include french fries or home fries. Substitute sweet potato fries or onion rings for an additional charge.' WHERE food_name = 'Italian Omelette Wrap' AND food_category = 'super-3-egg-wrap';
UPDATE food SET food_price = 13.95, food_desc = 'Jalapeno sauce. All wraps include french fries or home fries. Substitute sweet potato fries or onion rings for an additional charge.' WHERE food_name = 'Mexican Omelette Wrap' AND food_category = 'super-3-egg-wrap';
UPDATE food SET food_price = 13.95, food_desc = 'Ham and cheese. All wraps include french fries or home fries. Substitute sweet potato fries or onion rings for an additional charge.' WHERE food_name = 'American Omelette Wrap' AND food_category = 'super-3-egg-wrap';
UPDATE food SET food_price = 14.95, food_desc = 'Mixed vegetables. All wraps include french fries or home fries. Substitute sweet potato fries or onion rings for an additional charge.' WHERE food_name = 'Garden Omelette Wrap' AND food_category = 'super-3-egg-wrap';
UPDATE food SET food_price = 13.95, food_desc = 'Peppers and onions. All wraps include french fries or home fries. Substitute sweet potato fries or onion rings for an additional charge.' WHERE food_name = 'Oriental Omelette Wrap' AND food_category = 'super-3-egg-wrap';
UPDATE food SET food_price = 13.95, food_desc = 'Feta cheese and tomato. All wraps include french fries or home fries. Substitute sweet potato fries or onion rings for an additional charge.' WHERE food_name = 'Greek Omelette Wrap' AND food_category = 'super-3-egg-wrap';
UPDATE food SET food_price = 14.95, food_desc = 'Served with mozzarella cheese and no egg. All wraps include french fries or home fries. Substitute sweet potato fries or onion rings for an additional charge.' WHERE food_name = 'Vegetable Garden Omelette Wrap' AND food_category = 'super-3-egg-wrap';

-- ══ Cereal ══
UPDATE food SET food_price = 6.25, food_desc = 'Warm and comforting oatmeal to start your day.' WHERE food_name = 'Hot Oatmeal' AND food_category = 'cereal';
UPDATE food SET food_price = 10.95, food_desc = 'Warm oatmeal topped with a mix of fresh fruit.', food_star = 4.8 WHERE food_name = 'Hot Oatmeal with Fresh Fruit' AND food_category = 'cereal';

-- ══ Body Builder's Breakfast ══
UPDATE food SET food_price = 21.75, food_desc = 'Served with 6 turkey sausage or 6 strips of turkey bacon. Served with toast and home fries or steamed broccoli or choice of fruit cup or oatmeal cup.', food_star = 4.8 WHERE food_name = '6 Egg Whites Scrambled' AND food_category = 'body-builders';
UPDATE food SET food_price = 14.75, food_desc = 'Scrambled eggs with tomatoes, onions, cilantro, jalapenos and cheddar cheese. Served with toast and home fries or steamed broccoli or choice of fruit cup or oatmeal cup.' WHERE food_name = 'Huevos a la Mexicana' AND food_category = 'body-builders';
UPDATE food SET food_price = 21.75, food_desc = 'Served with fresh turkey, spinach, avocado and tomato. Served with toast and home fries or steamed broccoli or choice of fruit cup or oatmeal cup.' WHERE food_name = '6 Egg Whites Omelette' AND food_category = 'body-builders';
UPDATE food SET food_price = 21.75, food_desc = 'Protein-packed breakfast featuring scrambled egg whites and grilled chicken breast.' WHERE food_name = '6 Egg Whites Scrambled with Grilled Chicken Breast' AND food_category = 'body-builders';

-- ══ Bagels ══
UPDATE food SET food_price = 4.5, food_desc = 'Soft, toasted bagel topped with a generous helping of cream cheese.' WHERE food_name = 'Bagel with Smear of Cream Cheese' AND food_category = 'bagels';
UPDATE food SET food_price = 3.0, food_desc = 'Toasted bagel spread with butter and sweet jelly.' WHERE food_name = 'Bagel with Butter and Jelly' AND food_category = 'bagels';
UPDATE food SET food_price = 6.5, food_desc = 'Soft, toasted bagel smothered with a generous helping of cream cheese.' WHERE food_name = 'Bagel with Extra Cream Cheese' AND food_category = 'bagels';
UPDATE food SET food_price = 20.95, food_desc = 'Toasted bagel with a delicious spread.' WHERE food_name = 'Bagel All the Way' AND food_category = 'bagels';
UPDATE food SET food_price = 14.5, food_desc = 'Smoked salmon from Nova Scotia, paired with cream cheese on a toasted bagel.' WHERE food_name = 'Bagel with Nova Scotia Lox and Cream Cheese' AND food_category = 'bagels';
UPDATE food SET food_price = 13.5, food_desc = 'Smoked salmon from Nova Scotia, served on a toasted bagel.' WHERE food_name = 'Bagel with Nova Scotia Lox' AND food_category = 'bagels';
UPDATE food SET food_price = 25.95, food_desc = 'Cream cheese, nova Scotia lox, lettuce, tomato, onion, olives and 2 toasted bagels.' WHERE food_name = 'Bagel Platter for 2' AND food_category = 'bagels';

-- ══ Breakfast Extras ══
UPDATE food SET food_price = 4.5, food_desc = 'Hearty breakfast dish featuring corned beef and hash.' WHERE food_name = 'Corned Beef Hash Breakfast' AND food_category = 'breakfast-extras';
UPDATE food SET food_price = 4.5, food_desc = 'Savory sausage served with breakfast essentials.' WHERE food_name = 'Beef Sausage Breakfast' AND food_category = 'breakfast-extras';
UPDATE food SET food_price = 4.5, food_desc = 'Savory sausage made with turkey.', food_star = 4.8 WHERE food_name = 'Turkey Sausage' AND food_category = 'breakfast-extras';
UPDATE food SET food_price = 4.5, food_desc = 'Savory sausage served with breakfast essentials.' WHERE food_name = 'Sausage Breakfast' AND food_category = 'breakfast-extras';
UPDATE food SET food_price = 4.5, food_desc = 'Crispy bacon served with breakfast essentials.' WHERE food_name = 'Bacon Breakfast' AND food_category = 'breakfast-extras';
UPDATE food SET food_price = 3.0, food_desc = 'Spicy peppers add a kick to your breakfast.' WHERE food_name = 'Jalapeno Peppers Breakfast' AND food_category = 'breakfast-extras';
UPDATE food SET food_price = 4.5, food_desc = 'Canadian-style breakfast featuring crispy bacon.' WHERE food_name = 'Canadian Bacon Breakfast' AND food_category = 'breakfast-extras';
UPDATE food SET food_price = 3.0, food_desc = 'Fresh avocado added to your breakfast.' WHERE food_name = 'Avocado Breakfast' AND food_category = 'breakfast-extras';
UPDATE food SET food_price = 3.0, food_desc = 'Toasted bagel with breakfast accompaniments.' WHERE food_name = 'Bagel Breakfast' AND food_category = 'breakfast-extras';
UPDATE food SET food_price = 4.5, food_desc = 'Turkey bacon served with breakfast essentials.' WHERE food_name = 'Turkey Bacon Breakfast' AND food_category = 'breakfast-extras';
UPDATE food SET food_price = 4.5, food_desc = 'Ham served with breakfast items.' WHERE food_name = 'Ham Breakfast' AND food_category = 'breakfast-extras';

-- ══ Appetizers and Side Orders ══
UPDATE food SET food_price = 16.75, food_src = 'https://d1ralsognjng37.cloudfront.net/ed55b862-a6fb-4d6c-8b40-2effb856ed5a.jpeg', food_desc = '3 chicken fingers, 3 Buffalo wings, 3 mozzarella sticks and onion rings.' WHERE food_name = 'Appetizers Deluxe' AND food_category = 'appetizers';
UPDATE food SET food_price = 14.25, food_desc = 'Tender chicken strips served with crispy French fries.' WHERE food_name = 'Chicken Fingers with French Fries' AND food_category = 'appetizers';
UPDATE food SET food_price = 5.95, food_desc = 'Thinly sliced potatoes, crispy on the outside and fluffy inside.' WHERE food_name = 'Home Fries' AND food_category = 'appetizers';
UPDATE food SET food_price = 5.95, food_desc = 'Thinly sliced potatoes, crispy on the outside and fluffy within.', food_star = 4.8 WHERE food_name = 'French Fries' AND food_category = 'appetizers';
UPDATE food SET food_price = 4.75, food_desc = 'Tangy and crunchy accompaniment to your meal.' WHERE food_name = 'Pickles' AND food_category = 'appetizers';
UPDATE food SET food_price = 8.5, food_desc = 'Crispy sticks filled with melted mozzarella cheese.', food_star = 4.8 WHERE food_name = 'Mozzarella Sticks' AND food_category = 'appetizers';
UPDATE food SET food_price = 6.0, food_desc = 'Crisp, refreshing mix of shredded cabbage and more.' WHERE food_name = 'Coleslaw' AND food_category = 'appetizers';
UPDATE food SET food_price = 6.25, food_desc = 'Crispy sweet potato strips served as a side dish.' WHERE food_name = 'Sweet Potato Fries' AND food_category = 'appetizers';
UPDATE food SET food_price = 9.5, food_desc = 'Tender and juicy chicken strips, perfect for dipping.', food_star = 4.8 WHERE food_name = 'Chicken Fingers' AND food_category = 'appetizers';
UPDATE food SET food_price = 6.25, food_desc = 'Crispy, golden fries in a waffle shape.' WHERE food_name = 'Waffle Fries' AND food_category = 'appetizers';
UPDATE food SET food_price = 4.5, food_desc = 'Crispy strips of smoked turkey bacon.' WHERE food_name = 'Side of Turkey Bacon' AND food_category = 'appetizers';
UPDATE food SET food_price = 7.5, food_desc = 'Assorted vegetables served as a side dish.' WHERE food_name = 'Mixed Vegetables' AND food_category = 'appetizers';
UPDATE food SET food_price = 4.0, food_desc = 'Savory sausage served as a side dish.' WHERE food_name = 'Side of Sausage' AND food_category = 'appetizers';
UPDATE food SET food_price = 4.0, food_desc = 'Crispy strips of smoked pork belly.', food_star = 4.8 WHERE food_name = 'Side of Bacon' AND food_category = 'appetizers';
UPDATE food SET food_price = 5.5, food_desc = 'Smooth, creamy potatoes.' WHERE food_name = 'Mashed Potatoes' AND food_category = 'appetizers';
UPDATE food SET food_price = 8.95, food_desc = 'Crisp fries smothered in melted cheddar cheese.', food_star = 4.8 WHERE food_name = 'French Fries with Cheddar Cheese' AND food_category = 'appetizers';
UPDATE food SET food_price = 4.0, food_desc = 'Thinly sliced cured ham.' WHERE food_name = 'Side of Ham' AND food_category = 'appetizers';
UPDATE food SET food_price = 4.5, food_desc = 'Crispy shredded beef, perfect accompaniment to any meal.' WHERE food_name = 'Side of Corned Beef Hash' AND food_category = 'appetizers';
UPDATE food SET food_price = 8.25, food_desc = 'Fresh broccoli sautéed with aromatic garlic.' WHERE food_name = 'Sauteed Broccoli with Garlic' AND food_category = 'appetizers';
UPDATE food SET food_price = 5.5, food_desc = 'Fluffy, warm potato.' WHERE food_name = 'Baked Potato' AND food_category = 'appetizers';
UPDATE food SET food_price = 4.5, food_desc = 'Thinly sliced, cured bacon from Canada.' WHERE food_name = 'Side of Canadian Bacon' AND food_category = 'appetizers';
UPDATE food SET food_price = 4.5, food_desc = 'Juicy sausages made with beef.' WHERE food_name = 'Side of Beef Sausages' AND food_category = 'appetizers';
UPDATE food SET food_price = 5.75, food_desc = 'Sweet and tender potato.' WHERE food_name = 'Baked Sweet Potato' AND food_category = 'appetizers';
UPDATE food SET food_price = 3.0, food_desc = 'Fresh and creamy avocado served on the side.' WHERE food_name = 'Side of Avocado' AND food_category = 'appetizers';
UPDATE food SET food_price = 6.0, food_desc = 'Fresh lettuce and tomato served on the side.' WHERE food_name = 'Lettuce and Tomato Side' AND food_category = 'appetizers';
UPDATE food SET food_price = 6.5, food_desc = 'Crispy onion slices served as a tasty accompaniment.' WHERE food_name = 'Onion Rings' AND food_category = 'appetizers';
UPDATE food SET food_price = 6.25, food_desc = 'Steaming hot serving of rice.' WHERE food_name = 'Side of Rice' AND food_category = 'appetizers';
UPDATE food SET food_price = 8.25, food_desc = 'Crisp fries smothered in melted American cheese.' WHERE food_name = 'French Fries with American Cheese' AND food_category = 'appetizers';
UPDATE food SET food_price = 8.95, food_desc = 'Crispy fries smothered in melted mozzarella cheese.' WHERE food_name = 'French Fries with Mozzarella Cheese' AND food_category = 'appetizers';
UPDATE food SET food_price = 8.25, food_desc = 'Crispy fries smothered in melted American cheese.' WHERE food_name = 'Home Fries with American Cheese' AND food_category = 'appetizers';
UPDATE food SET food_price = 8.95, food_desc = 'Crispy fries smothered in melted mozzarella cheese.' WHERE food_name = 'Home Fries with Mozzarella Cheese' AND food_category = 'appetizers';
UPDATE food SET food_price = 8.95, food_desc = 'Crispy fries smothered in melted cheddar cheese.' WHERE food_name = 'Home Fries with Cheddar Cheese' AND food_category = 'appetizers';
UPDATE food SET food_price = 7.25, food_desc = 'Fresh selection of vegetables.' WHERE food_name = 'Vegetables' AND food_category = 'appetizers';
UPDATE food SET food_price = 6.0, food_desc = 'Creamy potato salad with a blend of flavors.' WHERE food_name = 'Potato Salad' AND food_category = 'appetizers';
UPDATE food SET food_price = 6.0, food_desc = 'Fresh and creamy cheese curd.' WHERE food_name = 'Cottage Cheese' AND food_category = 'appetizers';
UPDATE food SET food_price = 5.95, food_desc = 'Savoury Greek cheese with a tangy, salty flavor.' WHERE food_name = 'Feta Cheese' AND food_category = 'appetizers';
UPDATE food SET food_price = 3.0, food_desc = 'Spicy peppers adding a kick to your meal.' WHERE food_name = 'Side of Jalapenos' AND food_category = 'appetizers';
UPDATE food SET food_price = 4.5, food_desc = 'Savory sausage made with turkey.' WHERE food_name = 'Side of Turkey Sausage' AND food_category = 'appetizers';

-- ══ Cold Salad Platters ══
UPDATE food SET food_price = 15.0, food_desc = 'Fresh tuna mixed with greens, served on a platter.' WHERE food_name = 'Tuna Salad Platter' AND food_category = 'cold-salad-platters';
UPDATE food SET food_price = 15.95, food_desc = 'Individual tuna or salmon on a bed of lettuce with Cottage cheese and sliced tomato. Served with potato salad, coleslaw, sliced egg and garni.' WHERE food_name = 'Waist Watcher Salad Platter' AND food_category = 'cold-salad-platters';
UPDATE food SET food_price = 15.95, food_desc = 'Fresh sardines served on a bed of greens.' WHERE food_name = 'Individual Sardines Salad Platter' AND food_category = 'cold-salad-platters';
UPDATE food SET food_price = 15.95, food_desc = 'Sliced turkey or roast beef on a bed of crisp lettuce with ripe tomato and Cottage cheese. Served with potato salad, coleslaw, sliced egg and garni.' WHERE food_name = 'Spiro\'s Super Slim Line Salad Platter' AND food_category = 'cold-salad-platters';
UPDATE food SET food_price = 14.25, food_desc = 'Fresh eggs mixed with creamy dressing, served chilled.' WHERE food_name = 'Egg Salad Platter' AND food_category = 'cold-salad-platters';
UPDATE food SET food_price = 14.25, food_desc = 'Freshly prepared chicken mixed with greens and served on a platter.' WHERE food_name = 'Chicken Salad Platter' AND food_category = 'cold-salad-platters';
UPDATE food SET food_price = 15.95, food_desc = 'Fresh tuna mixed with greens, served on a platter.' WHERE food_name = 'Individual Tuna Salad Platter' AND food_category = 'cold-salad-platters';
UPDATE food SET food_price = 15.95, food_desc = 'Fresh salmon served on a bed of greens.' WHERE food_name = 'Individual Salmon Salad Platter' AND food_category = 'cold-salad-platters';

-- ══ Salads ══
UPDATE food SET food_price = 14.25, food_src = 'https://d1ralsognjng37.cloudfront.net/69195f2b-1807-4187-9814-62cce4a28129.jpeg', food_desc = 'Fresh mixed greens topped with grilled chicken.' WHERE food_name = 'House Salad with Grilled Chicken' AND food_category = 'salads';
UPDATE food SET food_price = 10.75, food_desc = 'Fresh mix of tomatoes, cucumbers, feta cheese, and olives.' WHERE food_name = 'Greek Salad' AND food_category = 'salads';
UPDATE food SET food_price = 14.95, food_desc = 'Tender grilled chicken on a bed of crisp romaine lettuce.' WHERE food_name = 'Caesar Salad with Grilled Chicken' AND food_category = 'salads';
UPDATE food SET food_price = 11.25, food_desc = 'On a bed of lettuce, tomato and cucumbers. Add avocado for an additional charge.' WHERE food_name = 'Tuna Salad' AND food_category = 'salads';
UPDATE food SET food_price = 9.25, food_desc = 'Crunchy romaine lettuce tossed with parmesan cheese and a tangy dressing.' WHERE food_name = 'Caesar Salad' AND food_category = 'salads';
UPDATE food SET food_price = 11.25, food_desc = 'On a bed of lettuce, tomato and cucumbers. Add avocado for an additional charge.' WHERE food_name = 'Egg Salad' AND food_category = 'salads';
UPDATE food SET food_price = 6.0, food_desc = 'Fresh mixed greens.' WHERE food_name = 'House Salad' AND food_category = 'salads';
UPDATE food SET food_price = 14.25, food_desc = 'Fresh tuna mixed with crisp greens in a refreshing salad.' WHERE food_name = 'House Salad with Tuna' AND food_category = 'salads';
UPDATE food SET food_price = 16.25, food_desc = 'Fresh mix of greens, grilled chicken, and feta cheese.' WHERE food_name = 'Greek Salad with Grilled Chicken' AND food_category = 'salads';
UPDATE food SET food_price = 15.25, food_desc = 'Mixed greens with a variety of toppings.' WHERE food_name = 'Chef\'s Salad' AND food_category = 'salads';
UPDATE food SET food_price = 11.25, food_desc = 'On a bed of lettuce, tomato and cucumbers. Add avocado for an additional charge.' WHERE food_name = 'Chicken Salad' AND food_category = 'salads';

-- ══ Tasty Sandwiches ══
UPDATE food SET food_price = 8.75, food_src = 'https://d1ralsognjng37.cloudfront.net/8c411d20-c1ec-4546-81e1-c9e569f49dd7.jpeg', food_desc = 'Classic egg salad served on bread.', food_star = 4.8 WHERE food_name = 'Egg Salad Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 7.75, food_desc = 'Crisp bacon, fresh lettuce, and juicy tomato on a sandwich.', food_star = 4.8 WHERE food_name = 'Bacon, Lettuce and Tomato Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 6.75, food_desc = 'Crisp bacon paired with two eggs, a classic combination.' WHERE food_name = 'Bacon and 2 Eggs Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 12.25, food_desc = 'Breaded and topped with melted mozzarella cheese.', food_star = 4.8 WHERE food_name = 'Chicken Parmigiana Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 8.75, food_desc = 'Fresh tuna mixed with greens, served on a sandwich.' WHERE food_name = 'Tuna Salad Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 6.75, food_desc = 'Savory sausage paired with two eggs.' WHERE food_name = 'Sausage and 2 Eggs Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 7.0, food_desc = 'Savory beef sausage paired with two eggs.' WHERE food_name = 'Beef Sausage and 2 Eggs Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 5.75, food_desc = 'Melted cheddar cheese between two slices of bread.' WHERE food_name = 'Grilled Cheddar Cheese Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 15.95, food_desc = 'Juicy chicken breast served on a toasted bun.' WHERE food_name = 'Grilled Chicken Deluxe Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 10.95, food_desc = 'Fresh avocado, crispy bacon, lettuce, and juicy tomato on a sandwich.' WHERE food_name = 'Avocado, Bacon, Lettuce and Tomato Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 8.25, food_desc = 'Thinly sliced turkey, crispy bacon, fresh lettuce, and juicy tomato on a sandwich.' WHERE food_name = 'Turkey Bacon, Lettuce and Tomato Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 5.25, food_desc = 'Crisp bacon and egg on a toasted sandwich.' WHERE food_name = 'Bacon and Egg Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 5.0, food_desc = 'Melted cheese between two slices of bread, a classic comfort food.' WHERE food_name = 'Grilled American Cheese Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 5.75, food_desc = 'Freshly made sandwich with potato and egg.' WHERE food_name = 'Potato and Egg Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 5.25, food_desc = 'Savory sausage paired with a fried egg.' WHERE food_name = 'Sausage and Egg Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 6.75, food_desc = 'Thinly sliced ham paired with two eggs.' WHERE food_name = 'Ham and 2 Eggs Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 8.5, food_desc = '2 eggs. Served with choice of bread.' WHERE food_name = 'Western Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 9.5, food_desc = 'Sliced turkey paired with two eggs in a sandwich.' WHERE food_name = 'Turkey with 2 Eggs Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 10.0, food_desc = 'Savoury sardines served on a sandwich.' WHERE food_name = 'Imported Skinless and Boneless Sardines Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 8.75, food_desc = 'Thinly sliced corned beef paired with two eggs.' WHERE food_name = 'Corned Beef and 2 Eggs Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 8.0, food_desc = 'Served with lettuce, tomato and mayonnaise. Served with choice of bread.' WHERE food_name = 'Avocado Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 10.0, food_desc = 'Fresh tuna served on a sandwich.' WHERE food_name = 'Individual Tuna Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 4.95, food_desc = 'Freshly made sandwich with 2 eggs.' WHERE food_name = '2 Eggs Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 7.75, food_desc = 'Crisp bacon served on a sandwich.' WHERE food_name = 'Bacon Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 7.75, food_desc = 'Thinly sliced ham served on bread.' WHERE food_name = 'Ham Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 10.95, food_desc = 'Crispy chicken cutlet served on a soft bun.' WHERE food_name = 'Fried Chicken Cutlet Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 4.0, food_desc = 'Egg sandwich with a crispy exterior and soft interior.' WHERE food_name = 'Fried Egg Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 5.95, food_desc = 'Savory beef sausage paired with a single egg.' WHERE food_name = 'Beef Sausage and 1 Egg Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 6.95, food_desc = 'Hard-boiled eggs served on sliced bread.' WHERE food_name = '2 Sliced Hard Boiled Egg Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 5.25, food_desc = 'Thinly sliced ham paired with a fresh egg.' WHERE food_name = 'Ham and Egg Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 5.75, food_desc = 'Savory turkey, crispy bacon, and egg on a sandwich.' WHERE food_name = 'Turkey Bacon and Egg Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 6.95, food_desc = 'Savory turkey bacon paired with two eggs.' WHERE food_name = 'Turkey Bacon and 2 Eggs Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 5.75, food_desc = 'Thinly sliced Canadian bacon paired with a fresh egg.' WHERE food_name = 'Canadian Bacon and Egg Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 8.75, food_desc = 'Thinly sliced pastrami paired with two eggs.' WHERE food_name = 'Pastrami and 2 Eggs Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 8.75, food_desc = 'Tender chicken mixed with greens, served on a sandwich.' WHERE food_name = 'Chicken Salad Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 6.95, food_desc = 'Classic melted cheese between two slices of bread.' WHERE food_name = 'American Cheese Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 7.25, food_desc = 'Thinly sliced Swiss cheese between two slices of bread.' WHERE food_name = 'Swiss Cheese Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 9.5, food_desc = 'Thinly sliced ham paired with melted American cheese.' WHERE food_name = 'Ham and American Cheese Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 5.75, food_desc = 'Melted Swiss cheese between two slices of bread, a classic comfort food.' WHERE food_name = 'Grilled Swiss Cheese Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 5.75, food_desc = 'Melted mozzarella cheese between two slices of bread.' WHERE food_name = 'Grilled Mozzarella Cheese Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 10.0, food_desc = 'Fresh salmon served on a sandwich.' WHERE food_name = 'Individual Salmon Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 11.95, food_desc = 'Tender fillet served on a sandwich.' WHERE food_name = 'Fried Fillet Sandwich' AND food_category = 'tasty-sandwiches';
UPDATE food SET food_price = 17.25, food_desc = 'Crispy fillet served with French fries.' WHERE food_name = 'Fried Fillet Sandwich with French Fries' AND food_category = 'tasty-sandwiches';

-- ══ Grilled Pita Sandwiches ══
UPDATE food SET food_price = 14.75, food_desc = 'Savory chicken, Swiss cheese, and mushrooms in a grilled pita.' WHERE food_name = 'Grilled Chicken, Swiss Cheese and Mushrooms Sandwich' AND food_category = 'grilled-pita';
UPDATE food SET food_price = 8.95, food_desc = 'Grilled pita filled with pizza ingredients.' WHERE food_name = 'Pizza Pita Sandwich' AND food_category = 'grilled-pita';
UPDATE food SET food_price = 10.5, food_desc = 'Fresh broccoli and melted cheese in a grilled pita.' WHERE food_name = 'Broccoli and Cheese Sandwich' AND food_category = 'grilled-pita';
UPDATE food SET food_price = 12.5, food_desc = 'Fresh spinach and crumbled feta in a grilled pita.' WHERE food_name = 'Spinach and Feta Sandwich' AND food_category = 'grilled-pita';
UPDATE food SET food_price = 12.5, food_desc = 'Fresh mozzarella, tomato, and mushroom come together in a flavorful combination.' WHERE food_name = 'Tomato, Mozzarella and Mushroom Sandwich' AND food_category = 'grilled-pita';
UPDATE food SET food_price = 11.5, food_desc = 'Smoky eggplant paired with tangy balsamic vinegar on a toasted pita.' WHERE food_name = 'Grilled Eggplant with Balsamic Vinegar Sandwich' AND food_category = 'grilled-pita';
UPDATE food SET food_price = 16.0, food_desc = 'Tender grilled chicken and eggplant, finished with a tangy balsamic vinegar.' WHERE food_name = 'Grilled Chicken and Eggplant with Balsamic Vinegar Sandwich' AND food_category = 'grilled-pita';

-- ══ Grilled Chicken Sandwiches ══
UPDATE food SET food_price = 14.25, food_desc = 'Juicy chicken, crispy bacon, fresh lettuce, and ripe tomato on a toasted bun.' WHERE food_name = 'Grilled Chicken Sandwich with Bacon, Lettuce and Tomato' AND food_category = 'grilled-chicken-sandwiches';
UPDATE food SET food_price = 10.25, food_desc = 'Tender chicken breast served on a toasted bun.', food_star = 4.8 WHERE food_name = 'Grilled Chicken Sandwich' AND food_category = 'grilled-chicken-sandwiches';
UPDATE food SET food_price = 12.25, food_desc = 'Tender chicken, onions, and peppers come together in a flavorful sandwich.' WHERE food_name = 'Grilled Chicken Sandwich with Onions and Peppers' AND food_category = 'grilled-chicken-sandwiches';
UPDATE food SET food_price = 12.75, food_desc = 'Tender grilled chicken paired with fresh tomato and melted mozzarella.' WHERE food_name = 'Grilled Chicken Sandwich with Tomato and Mozzarella' AND food_category = 'grilled-chicken-sandwiches';
UPDATE food SET food_price = 17.0, food_desc = 'Served with avocado, lettuce, tomato and chipotle mayo on a roll. Sandwiches served on rolls.' WHERE food_name = 'Chipotle Fried Chicken Cutlet' AND food_category = 'grilled-chicken-sandwiches';
UPDATE food SET food_price = 13.75, food_desc = 'Tender chicken, Swiss cheese, and sautéed mushrooms on a toasted bun.' WHERE food_name = 'Grilled Chicken Sandwich with Swiss and Mushrooms' AND food_category = 'grilled-chicken-sandwiches';
UPDATE food SET food_price = 14.95, food_desc = 'Savory chicken, crispy bacon, and melted cheddar cheese come together in perfect harmony.' WHERE food_name = 'Grilled Chicken Sandwich with Bacon and Cheddar Cheese' AND food_category = 'grilled-chicken-sandwiches';
UPDATE food SET food_price = 14.75, food_desc = 'Cordon blue. Sandwiches served on rolls.' WHERE food_name = 'Grilled Chicken Sandwich with Swiss and Ham' AND food_category = 'grilled-chicken-sandwiches';

-- ══ Special Sandwiches ══
UPDATE food SET food_price = 13.25, food_desc = 'Corned beef, sauerkraut and Swiss cheese on rye.' WHERE food_name = 'Reuben Sandwich' AND food_category = 'special-sandwiches';
UPDATE food SET food_price = 16.95, food_desc = 'Served with cheese, onions and peppers.' WHERE food_name = 'Philly Cheese Steak Hero with French Fries' AND food_category = 'special-sandwiches';
UPDATE food SET food_price = 17.75, food_desc = 'Corned beef, sauerkraut and Swiss cheese on rye.' WHERE food_name = 'Reuben Sandwich with French Fries' AND food_category = 'special-sandwiches';
UPDATE food SET food_price = 11.5, food_desc = 'Grilled cheese topped with tuna and tomato.' WHERE food_name = 'Tuna Melt' AND food_category = 'special-sandwiches';
UPDATE food SET food_price = 14.0, food_desc = 'Served with cheese, onions and peppers.' WHERE food_name = 'Chicken Philly Cheese Hero' AND food_category = 'special-sandwiches';
UPDATE food SET food_price = 13.5, food_desc = 'Served with cheese, onions and peppers.' WHERE food_name = 'Philly Cheese Steak Hero' AND food_category = 'special-sandwiches';
UPDATE food SET food_price = 15.25, food_desc = 'Grilled cheese topped with tuna and tomato on rye bread.' WHERE food_name = 'Tuna Melt with French Fries' AND food_category = 'special-sandwiches';
UPDATE food SET food_price = 17.95, food_desc = 'Served with cheese, onions and peppers.' WHERE food_name = 'Chicken Philly Cheese Hero with French Fries' AND food_category = 'special-sandwiches';
UPDATE food SET food_price = 14.5, food_desc = 'Open face grilled cheese with bacon, tomato and french fries.' WHERE food_name = 'Happy Waitress Sandwich' AND food_category = 'special-sandwiches';
UPDATE food SET food_price = 22.5, food_desc = 'Strips of steak on toasted garlic roll with melted mozzarella and french fries. .' WHERE food_name = 'Milano Sandwich' AND food_category = 'special-sandwiches';

-- ══ Hot Open Sandwiches ══
UPDATE food SET food_price = 20.95, food_desc = 'Thinly sliced beef served on a bed of bread.' WHERE food_name = 'Roast Beef Sandwich' AND food_category = 'hot-open-sandwiches';
UPDATE food SET food_price = 20.95, food_desc = 'Tender brisket served on a sandwich.' WHERE food_name = 'Brisket Sandwich' AND food_category = 'hot-open-sandwiches';
UPDATE food SET food_price = 20.95, food_desc = 'Thinly sliced ham served on a bed of fresh greens.' WHERE food_name = 'Virginia Ham Sandwich' AND food_category = 'hot-open-sandwiches';
UPDATE food SET food_price = 22.5, food_desc = 'Thinly sliced turkey served on a bed of fresh bread.' WHERE food_name = 'Sliced Turkey Sandwich' AND food_category = 'hot-open-sandwiches';

-- ══ Classic Burgers ══
UPDATE food SET food_price = 9.5, food_desc = 'Juicy beef patty topped with melted cheese.' WHERE food_name = 'Cheeseburger' AND food_category = 'classic-burgers';
UPDATE food SET food_price = 8.75, food_desc = 'Juicy beef patty served on a bun.' WHERE food_name = 'Hamburger' AND food_category = 'classic-burgers';
UPDATE food SET food_price = 11.25, food_desc = 'Juicy beef patty topped with crispy bacon and melted cheese.' WHERE food_name = 'Cheeseburger with Bacon' AND food_category = 'classic-burgers';
UPDATE food SET food_price = 9.25, food_desc = 'Juicy turkey patty served on a bun.' WHERE food_name = 'Turkey Burger' AND food_category = 'classic-burgers';
UPDATE food SET food_price = 10.75, food_desc = 'Juicy beef patty topped with crispy bacon.' WHERE food_name = 'Hamburger with Bacon' AND food_category = 'classic-burgers';
UPDATE food SET food_price = 9.5, food_desc = 'Juicy beef patty topped with Swiss cheese.' WHERE food_name = 'Swiss Burger' AND food_category = 'classic-burgers';
UPDATE food SET food_price = 9.5, food_desc = 'Juicy beef patty topped with melted mozzarella cheese.' WHERE food_name = 'Mozzarella Burger' AND food_category = 'classic-burgers';
UPDATE food SET food_price = 9.5, food_desc = 'Juicy beef patty topped with melted cheddar cheese.' WHERE food_name = 'Cheddar Burger' AND food_category = 'classic-burgers';
UPDATE food SET food_price = 9.25, food_desc = 'Juicy patty topped with sautéed mushrooms.' WHERE food_name = 'Mushroom Burger' AND food_category = 'classic-burgers';
UPDATE food SET food_price = 9.25, food_desc = 'A burger patty topped with pizza sauce and melted mozzarella cheese.' WHERE food_name = 'Pizza Burger' AND food_category = 'classic-burgers';
UPDATE food SET food_price = 9.0, food_desc = 'Freshly made burger with garden-inspired flavors.' WHERE food_name = 'Garden Burger' AND food_category = 'classic-burgers';

-- ══ Classic Burger Deluxe ══
UPDATE food SET food_price = 15.5, food_src = 'https://d1ralsognjng37.cloudfront.net/565792d6-414d-4ed8-8fb5-5de192419e1b.jpeg', food_desc = 'Juicy beef patty, crispy bacon, and melted cheese.' WHERE food_name = 'Cheeseburger with Bacon Deluxe' AND food_category = 'classic-burger-deluxe';
UPDATE food SET food_price = 12.75, food_desc = 'Juicy beef patty topped with cheese and served on a toasted bun.' WHERE food_name = 'Hamburger Deluxe' AND food_category = 'classic-burger-deluxe';
UPDATE food SET food_price = 13.75, food_desc = 'Juicy beef patty topped with cheese.' WHERE food_name = 'Cheesburger Deluxe' AND food_category = 'classic-burger-deluxe';
UPDATE food SET food_price = 14.25, food_desc = 'Juicy beef patty topped with cheddar cheese.' WHERE food_name = 'Cheddar Burger Deluxe' AND food_category = 'classic-burger-deluxe';
UPDATE food SET food_price = 14.25, food_desc = 'Juicy turkey patty topped with fresh ingredients.' WHERE food_name = 'Turkey Burger Deluxe' AND food_category = 'classic-burger-deluxe';
UPDATE food SET food_price = 14.5, food_desc = 'Juicy beef patty topped with crispy bacon.' WHERE food_name = 'Hamburger with Bacon Deluxe' AND food_category = 'classic-burger-deluxe';
UPDATE food SET food_price = 14.25, food_desc = 'Juicy beef patty topped with Swiss cheese and served on a toasted bun.' WHERE food_name = 'Swiss Burger Deluxe' AND food_category = 'classic-burger-deluxe';
UPDATE food SET food_price = 14.25, food_desc = 'Juicy beef patty topped with mozzarella cheese.' WHERE food_name = 'Mozzarella Burger Deluxe' AND food_category = 'classic-burger-deluxe';
UPDATE food SET food_price = 14.5, food_desc = 'Juicy beef patty topped with sautéed mushrooms.' WHERE food_name = 'Mushroom Burger Deluxe' AND food_category = 'classic-burger-deluxe';
UPDATE food SET food_price = 14.25, food_desc = 'Juicy beef patty, melted cheese, and savory sauce on a toasted bun.' WHERE food_name = 'Pizza Burger Deluxe' AND food_category = 'classic-burger-deluxe';
UPDATE food SET food_price = 14.25, food_desc = 'Juicy beef patty topped with fresh garden greens.' WHERE food_name = 'Garden Burger Deluxe' AND food_category = 'classic-burger-deluxe';

-- ══ Specialty Burgers ══
UPDATE food SET food_price = 16.25, food_desc = 'Topped with bacon, mushrooms, Swiss cheese and onions. Add bacon extra for each burger. Substitute sweet potato fries or onion rings, extra avocado for an additional charge.' WHERE food_name = 'Spiro\'s Super Burger Deluxe' AND food_category = 'specialty-burgers';
UPDATE food SET food_price = 19.0, food_desc = 'Served with french fries, lettuce and tomato. Add bacon extra for each burger. Substitute sweet potato fries or onion rings, extra avocado for an additional charge.', food_star = 4.8 WHERE food_name = 'Twin Cheeseburger Deluxe' AND food_category = 'specialty-burgers';
UPDATE food SET food_price = 14.75, food_desc = 'Served with french fries, lettuce, tomato and onions. Add bacon extra for each burger. Substitute sweet potato fries or onion rings, extra avocado for an additional charge.' WHERE food_name = 'Jalapeno Cheeseburger Deluxe' AND food_category = 'specialty-burgers';
UPDATE food SET food_price = 17.25, food_desc = 'On a pita with feta cheese, served with french fries. Add bacon extra for each burger. Substitute sweet potato fries or onion rings, extra avocado for an additional charge.' WHERE food_name = 'Greek Burger' AND food_category = 'specialty-burgers';
UPDATE food SET food_price = 14.75, food_desc = 'Served on a bed of lettuce and tomato with Cottage cheese. Add bacon extra for each burger. Substitute sweet potato fries or onion rings, extra avocado for an additional charge.' WHERE food_name = 'Lo-Cal Turkey Burger' AND food_category = 'specialty-burgers';
UPDATE food SET food_price = 17.5, food_desc = 'Served with french fries, lettuce and tomato. Add bacon extra for each burger. Substitute sweet potato fries or onion rings, extra avocado for an additional charge.' WHERE food_name = 'Twin Burger Deluxe' AND food_category = 'specialty-burgers';
UPDATE food SET food_price = 14.5, food_desc = 'Served with fried egg, served with french fries and tomato. Add bacon extra for each burger. Substitute sweet potato fries or onion rings, extra avocado for an additional charge.', food_star = 4.8 WHERE food_name = 'Southern Burger' AND food_category = 'specialty-burgers';
UPDATE food SET food_price = 16.25, food_desc = 'Served with bacon, cheddar cheese, fried onions and BBQ sauce, served with french fries. Add bacon extra for each burger. Substitute sweet potato fries or onion rings, extra avocado for an additional charge.' WHERE food_name = 'Texas Burger' AND food_category = 'specialty-burgers';
UPDATE food SET food_price = 14.5, food_desc = 'Served on a bed of lettuce and tomato with Cottage cheese. Add bacon extra for each burger. Substitute sweet potato fries or onion rings, extra avocado for an additional charge.' WHERE food_name = 'Lo-Cal Burger' AND food_category = 'specialty-burgers';

-- ══ Slim Line ══
UPDATE food SET food_price = 16.95, food_desc = 'Assortment of four hot vegetables.' WHERE food_name = '4 Hot Vegetables Platter' AND food_category = 'slim-line';
UPDATE food SET food_price = 14.95, food_desc = 'Fresh fruit salad, Cottage cheese and jello on crisp lettuce. Served with lettuce, tomato and fresh fruit.' WHERE food_name = 'California Health Salad' AND food_category = 'slim-line';
UPDATE food SET food_price = 11.95, food_desc = 'Served with Cottage cheese. Served with lettuce, tomato and fresh fruit.' WHERE food_name = '1/2 Melon' AND food_category = 'slim-line';
UPDATE food SET food_price = 14.25, food_desc = 'Broiled hamburger served with Cottage cheese on a bed of lettuce and tomato. Served with lettuce, tomato and fresh fruit.' WHERE food_name = 'Lo-Cal Burger' AND food_category = 'slim-line';
UPDATE food SET food_price = 15.75, food_desc = 'Served with lettuce, tomato and fresh fruit. Served with lettuce, tomato and fresh fruit.' WHERE food_name = 'Tuna Salad' AND food_category = 'slim-line';

-- ══ Triple Decker Clubs ══
UPDATE food SET food_price = 16.95, food_desc = 'Thinly sliced turkey, crispy bacon, and fresh lettuce on toasted bread.' WHERE food_name = 'Turkey with Bacon Club' AND food_category = 'triple-decker-clubs';
UPDATE food SET food_price = 16.5, food_desc = 'Tender chicken, crispy bacon, and fresh greens come together in a triple-decker club.' WHERE food_name = 'Chicken Salad with Bacon Club' AND food_category = 'triple-decker-clubs';
UPDATE food SET food_price = 17.5, food_desc = 'Tender chicken, crispy bacon, and fresh ingredients come together in this triple-decker club.' WHERE food_name = 'Grilled Chicken with Bacon Club' AND food_category = 'triple-decker-clubs';
UPDATE food SET food_price = 16.5, food_desc = 'Thinly sliced Virginia ham and Swiss cheese layered in a triple decker club.' WHERE food_name = 'Virginia Ham and Swiss Club' AND food_category = 'triple-decker-clubs';
UPDATE food SET food_price = 16.5, food_desc = 'Thinly sliced roast beef paired with crispy bacon.' WHERE food_name = 'Roast Beef with Bacon Club' AND food_category = 'triple-decker-clubs';
UPDATE food SET food_price = 16.5, food_desc = 'Fresh tuna salad and sliced egg layered in a triple decker club.' WHERE food_name = 'Tuna Salad and Sliced Egg Club' AND food_category = 'triple-decker-clubs';
UPDATE food SET food_price = 16.5, food_desc = 'Crisp bacon and fresh egg salad layered in a triple decker club.' WHERE food_name = 'Egg Salad with Bacon Club' AND food_category = 'triple-decker-clubs';

-- ══ Carving Board Sandwiches ══
UPDATE food SET food_price = 11.0, food_desc = 'Thinly sliced pastrami served on a carving board.' WHERE food_name = 'Pastrami Carving Board Sandwich' AND food_category = 'carving-board';
UPDATE food SET food_price = 11.25, food_desc = 'Thinly sliced corned beef served on a carving board.' WHERE food_name = 'Corned Beef Carving Board Sandwich' AND food_category = 'carving-board';
UPDATE food SET food_price = 11.0, food_desc = 'Tender meatloaf served on a carving board with fresh accompaniments.' WHERE food_name = 'Meatloaf Carving Board Sandwich' AND food_category = 'carving-board';
UPDATE food SET food_price = 11.25, food_desc = 'Thinly sliced turkey served on a carving board.' WHERE food_name = 'Sliced Turkey Carving Board Sandwich' AND food_category = 'carving-board';
UPDATE food SET food_price = 11.0, food_desc = 'Thinly sliced roast beef served on a carving board.' WHERE food_name = 'Roast Beef Carving Board Sandwich' AND food_category = 'carving-board';
UPDATE food SET food_price = 11.0, food_desc = 'Thinly sliced brisket served on a carving board.' WHERE food_name = 'Brisket Carving Board Sandwich' AND food_category = 'carving-board';
UPDATE food SET food_price = 11.0, food_desc = 'Thinly sliced Virginia ham served on a carving board.' WHERE food_name = 'Virginia Ham Carving Board Sandwich' AND food_category = 'carving-board';
UPDATE food SET food_price = 14.95, food_desc = 'Thinly sliced London broil served on a carving board.' WHERE food_name = 'London Broil Carving Board Sandwich' AND food_category = 'carving-board';

-- ══ Our New Gourmet Wraps ══
UPDATE food SET food_price = 14.5, food_desc = 'Tender grilled chicken, crisp romaine lettuce, and tangy Caesar dressing wrapped in a fresh tortilla.' WHERE food_name = 'Grilled Chicken Caesar Salad Wrap' AND food_category = 'gourmet-wraps';
UPDATE food SET food_price = 14.5, food_desc = 'Served with lettuce, tomato and honey mustard. Choice of regular or whole wheat wrap. Served on grilled flatbread with choice of side.' WHERE food_name = 'Chicken Finger Wrap' AND food_category = 'gourmet-wraps';
UPDATE food SET food_price = 17.0, food_desc = 'Sliced turkey, crispy bacon, and fresh lettuce wrapped in a tortilla.' WHERE food_name = 'Turkey B.L.T. Wrap' AND food_category = 'gourmet-wraps';
UPDATE food SET food_price = 17.0, food_desc = 'Tender steak and melted cheese wrapped in a flavorful package.' WHERE food_name = 'Philly Cheese Steak Wrap' AND food_category = 'gourmet-wraps';
UPDATE food SET food_price = 17.25, food_desc = 'Tender chicken, crispy bacon, and creamy ranch in a wrap.' WHERE food_name = 'Chicken Bacon Ranch Wrap' AND food_category = 'gourmet-wraps';
UPDATE food SET food_price = 14.5, food_desc = 'Served with lettuce and tomato. Choice of regular or whole wheat wrap. Served on grilled flatbread with choice of side.' WHERE food_name = 'Egg Salad Wrap' AND food_category = 'gourmet-wraps';
UPDATE food SET food_price = 14.5, food_desc = 'Served with grilled chicken, spinach and feta cheese. Choice of regular or whole wheat wrap. Served on grilled flatbread with choice of side.' WHERE food_name = 'Florentine Wrap' AND food_category = 'gourmet-wraps';
UPDATE food SET food_price = 14.5, food_desc = 'Tender grilled chicken, mixed greens, and feta in a crispy wrap.' WHERE food_name = 'Grilled Chicken Greek Salad Wrap' AND food_category = 'gourmet-wraps';
UPDATE food SET food_price = 14.5, food_desc = 'Served with grilled chicken, onions and peppers. Choice of regular or whole wheat wrap. Served on grilled flatbread with choice of side.' WHERE food_name = 'Oriental Wrap' AND food_category = 'gourmet-wraps';
UPDATE food SET food_price = 14.95, food_desc = 'Fresh vegetables wrapped with mozzarella cheese.' WHERE food_name = 'Vegetable Garden Wrap with Mozzarella' AND food_category = 'gourmet-wraps';
UPDATE food SET food_price = 14.5, food_desc = 'Served with lettuce and tomato. Choice of regular or whole wheat wrap. Served on grilled flatbread with choice of side.' WHERE food_name = 'Tuna Salad Wrap' AND food_category = 'gourmet-wraps';
UPDATE food SET food_price = 14.5, food_desc = 'Served with lettuce and tomato. Choice of regular or whole wheat wrap. Served on grilled flatbread with choice of side.' WHERE food_name = 'Chicken Salad Wrap' AND food_category = 'gourmet-wraps';
UPDATE food SET food_price = 14.5, food_desc = 'Mixed greens, grilled chicken, and a blend of flavors in a wrap.' WHERE food_name = 'Grilled Chicken Mixed Salad Wrap' AND food_category = 'gourmet-wraps';

-- ══ Steaks and Chops ══
UPDATE food SET food_price = 22.25, food_desc = 'Served with fried onions. Served with salad, potato and vegetables.' WHERE food_name = 'Chopped Steak' AND food_category = 'steaks-chops';
UPDATE food SET food_price = 26.95, food_desc = 'Tender steak with a rich flavor.' WHERE food_name = 'Roumanian Steak' AND food_category = 'steaks-chops';
UPDATE food SET food_price = 28.5, food_desc = 'Romanian steak topped with mushrooms in a Marsala sauce. Served with salad, potato and vegetables.' WHERE food_name = 'Steak Delight' AND food_category = 'steaks-chops';
UPDATE food SET food_price = 22.75, food_desc = 'Tender turkey steak, expertly chopped for a satisfying bite.' WHERE food_name = 'Turkey Chopped Steak' AND food_category = 'steaks-chops';
UPDATE food SET food_price = 26.95, food_desc = 'Tender cut of beef, expertly seasoned and grilled to perfection.' WHERE food_name = 'London Broil' AND food_category = 'steaks-chops';
UPDATE food SET food_price = 23.95, food_desc = 'Thinly sliced ham steak, cured to perfection.' WHERE food_name = 'Virginia Ham Steak' AND food_category = 'steaks-chops';

-- ══ Sautes ══
UPDATE food SET food_price = 22.95, food_desc = 'Tender chicken in a rich and creamy sauce.' WHERE food_name = 'Chicken Francaise' AND food_category = 'sautes';
UPDATE food SET food_price = 22.95, food_desc = 'Tender chicken in a rich Marsala sauce.' WHERE food_name = 'Chicken Marsala' AND food_category = 'sautes';
UPDATE food SET food_price = 22.95, food_desc = 'Tender chicken in a zesty scampi sauce.' WHERE food_name = 'Chicken Scampi' AND food_category = 'sautes';

-- ══ Broiled Seafood ══
UPDATE food SET food_price = 22.95, food_desc = 'Fresh salmon, expertly broiled to bring out its natural flavors.' WHERE food_name = 'Broiled Salmon' AND food_category = 'broiled-seafood';
UPDATE food SET food_price = 22.95, food_desc = 'Delicate filet of sole, expertly broiled to bring out its natural flavors.' WHERE food_name = 'Broiled Filet of Sole' AND food_category = 'broiled-seafood';

-- ══ Fried Seafood ══
UPDATE food SET food_price = 22.95, food_desc = 'Delicate filet of sole, lightly battered and fried to a crispy golden brown.' WHERE food_name = 'Fried Filet of Sole' AND food_category = 'fried-seafood';

-- ══ Entrees and Roasts ══
UPDATE food SET food_price = 22.95, food_desc = 'Classic comfort food made with ground meat.' WHERE food_name = 'Meatloaf' AND food_category = 'entrees-roasts';
UPDATE food SET food_price = 23.95, food_desc = 'Tender turkey, roasted to perfection.' WHERE food_name = 'Roast Turkey' AND food_category = 'entrees-roasts';
UPDATE food SET food_price = 23.25, food_desc = 'Tender and juicy chicken breast, expertly grilled to perfection.' WHERE food_name = 'Grilled Chicken Breast' AND food_category = 'entrees-roasts';
UPDATE food SET food_price = 22.95, food_desc = 'Tender beef brisket, slow-cooked to perfection.' WHERE food_name = 'Brisket of Beef' AND food_category = 'entrees-roasts';
UPDATE food SET food_price = 22.95, food_desc = 'Tender and juicy chicken, roasted to perfection.' WHERE food_name = 'Roast Chicken' AND food_category = 'entrees-roasts';
UPDATE food SET food_price = 22.95, food_desc = 'Tender beef, roasted to perfection.' WHERE food_name = 'Roast Beef' AND food_category = 'entrees-roasts';

-- ══ Spaghetti ══
UPDATE food SET food_price = 11.25, food_desc = 'Tender spaghetti tossed in a rich and tangy marinara sauce.' WHERE food_name = 'Spaghetti with Marinara Sauce' AND food_category = 'spaghetti';
UPDATE food SET food_price = 16.95, food_desc = 'Tender meatballs served with spaghetti.' WHERE food_name = 'Spaghetti with Meatballs' AND food_category = 'spaghetti';
UPDATE food SET food_price = 12.5, food_desc = 'Tender spaghetti tossed with garlic and oil.' WHERE food_name = 'Spaghetti with Garlic and Oil' AND food_category = 'spaghetti';
UPDATE food SET food_price = 18.75, food_desc = 'Tender spaghetti tossed in a rich meat sauce.' WHERE food_name = 'Spaghetti with Meat Sauce' AND food_category = 'spaghetti';
UPDATE food SET food_price = 18.5, food_desc = 'Tender fish cakes served with spaghetti.' WHERE food_name = 'Spaghetti with Fish Cakes' AND food_category = 'spaghetti';

-- ══ Italian Specialties ══
UPDATE food SET food_price = 22.95, food_desc = 'Breaded and topped with melted mozzarella cheese.' WHERE food_name = 'Chicken Parmigiana' AND food_category = 'italian-specialties';
UPDATE food SET food_price = 21.25, food_desc = 'Breaded and topped with melted mozzarella cheese.' WHERE food_name = 'Eggplant Parmigiana' AND food_category = 'italian-specialties';
UPDATE food SET food_price = 24.25, food_desc = 'Breaded and topped with melted mozzarella, served with eggplant.' WHERE food_name = 'Chicken and Eggplant Parmigiana' AND food_category = 'italian-specialties';

-- ══ Greek Specialties ══
UPDATE food SET food_price = 9.0, food_desc = 'Beef or chicken. Served in warm pita bread with tzatziki sauce, lettuce, tomato and onions. Substitute sweet potato fries or onion rings for an additional charge.' WHERE food_name = 'Gyro' AND food_category = 'greek-specialties';
UPDATE food SET food_price = 17.0, food_desc = 'Beef or chicken. Served in warm pita bread with lettuce, tomato, onions, french fries, small Greek salad and tzatziki sauce. Substitute sweet potato fries or onion rings for an additional charge.' WHERE food_name = 'Gyro Platter' AND food_category = 'greek-specialties';
UPDATE food SET food_price = 17.95, food_desc = 'Chunks of marinated chicken breast served in warm pita bread with french fries, small Greek salad and tzatziki sauce. Substitute sweet potato fries or onion rings for an additional charge.' WHERE food_name = 'Chicken Souvlaki Platter' AND food_category = 'greek-specialties';
UPDATE food SET food_price = 15.25, food_desc = 'Spinach pie. Substitute sweet potato fries or onion rings for an additional charge.' WHERE food_name = 'Spanakopita with Greek Salad' AND food_category = 'greek-specialties';
UPDATE food SET food_price = 8.95, food_desc = 'Spinach pie. Substitute sweet potato fries or onion rings for an additional charge.' WHERE food_name = 'Spanakopita' AND food_category = 'greek-specialties';
UPDATE food SET food_price = 11.95, food_desc = 'Chunks of marinated chicken breast served in warm pita bread with tzatziki sauce, lettuce tomato and onions. Substitute sweet potato fries or onion rings for an additional charge.' WHERE food_name = 'Chicken Souvlaki' AND food_category = 'greek-specialties';

-- ══ Chef Specials ══
UPDATE food SET food_price = 23.95, food_desc = 'Over rice.' WHERE food_name = 'Chicken Kabob' AND food_category = 'chef-specials';
UPDATE food SET food_price = 22.95, food_desc = 'Served with soup or salad, potato and vegetable.' WHERE food_name = 'Chicken Cordon Blue' AND food_category = 'chef-specials';
UPDATE food SET food_price = 15.5, food_desc = 'Spring-inspired mix of vegetables and pasta.' WHERE food_name = 'Pasta Primavera' AND food_category = 'chef-specials';
UPDATE food SET food_price = 24.95, food_desc = 'Sauteed chicken and broccoli topped with mozzarella cheese in a light marinara and francaise sauce, served with soup or salad and pasta or potato and vegetable.' WHERE food_name = 'Chicken a la Floka' AND food_category = 'chef-specials';
UPDATE food SET food_price = 22.95, food_desc = 'Over rice.' WHERE food_name = 'Chicken Teriyaki' AND food_category = 'chef-specials';
UPDATE food SET food_price = 24.95, food_desc = 'Onions, peppers and mushrooms sauteed in a special sauce. Served with pasta or potato and vegetable.' WHERE food_name = 'Chicken Scarmadella' AND food_category = 'chef-specials';
UPDATE food SET food_price = 26.95, food_desc = 'Over rice.' WHERE food_name = 'Beef Kabob' AND food_category = 'chef-specials';

-- ══ Fruits and Puddings ══
UPDATE food SET food_price = 6.25, food_desc = 'Fresh seasonal fruits served in a cup.' WHERE food_name = 'Fruit Cup' AND food_category = 'fruits-puddings';
UPDATE food SET food_price = 6.25, food_desc = 'A mix of fresh seasonal fruits.' WHERE food_name = 'Fresh Fruit Cocktail' AND food_category = 'fruits-puddings';
UPDATE food SET food_price = 6.95, food_desc = 'Fresh seasonal melon, perfect for a sweet and refreshing treat.', food_star = 4.8 WHERE food_name = 'Fresh Melon in Season' AND food_category = 'fruits-puddings';
UPDATE food SET food_price = 5.95, food_desc = 'Creamy dessert made with rice.' WHERE food_name = 'Rice Pudding' AND food_category = 'fruits-puddings';
UPDATE food SET food_price = 5.75, food_desc = 'Sweet and refreshing dessert made from gelatin.', food_star = 4.8 WHERE food_name = 'Jello' AND food_category = 'fruits-puddings';
UPDATE food SET food_price = 5.95, food_desc = 'Rich and creamy dessert made with chocolate.' WHERE food_name = 'Chocolate Pudding' AND food_category = 'fruits-puddings';

-- ══ Danish and Muffins ══
UPDATE food SET food_price = 3.0, food_desc = 'Sweet pastry filled with cinnamon.' WHERE food_name = 'Cinnamon Danish' AND food_category = 'danish-muffins';
UPDATE food SET food_price = 3.0, food_desc = 'Flaky pastry filled with melted cheese.', food_star = 4.8 WHERE food_name = 'Cheese Danish' AND food_category = 'danish-muffins';
UPDATE food SET food_price = 3.0, food_desc = 'Moist and flavorful corn-based treat.' WHERE food_name = 'Corn Muffin' AND food_category = 'danish-muffins';
UPDATE food SET food_price = 3.0, food_desc = 'Sweet blueberry treat, perfect for a morning pick-me-up.' WHERE food_name = 'Blueberry Muffin' AND food_category = 'danish-muffins';
UPDATE food SET food_price = 3.0, food_desc = 'Wholesome muffin made with bran.' WHERE food_name = 'Bran Muffin' AND food_category = 'danish-muffins';
UPDATE food SET food_price = 2.75, food_desc = 'Freshly baked bread, perfect for a quick snack or breakfast.', food_star = 4.8 WHERE food_name = 'Toast' AND food_category = 'danish-muffins';
UPDATE food SET food_price = 3.0, food_desc = 'Moist and rich dessert cake.' WHERE food_name = 'Pound Cake' AND food_category = 'danish-muffins';
UPDATE food SET food_price = 3.0, food_desc = 'Traditional Eastern European-style bread with a depression in the center.' WHERE food_name = 'Bialy' AND food_category = 'danish-muffins';
UPDATE food SET food_price = 3.0, food_desc = 'Soft, chewy bread in a classic ring shape.' WHERE food_name = 'Bagel' AND food_category = 'danish-muffins';
UPDATE food SET food_price = 3.0, food_desc = 'Soft and fluffy bread, perfect for toasting.' WHERE food_name = 'English Muffin' AND food_category = 'danish-muffins';
UPDATE food SET food_price = 2.75, food_desc = 'Sweet pastry treat.' WHERE food_name = 'Roll' AND food_category = 'danish-muffins';

-- ══ Pies and Cakes ══
UPDATE food SET food_price = 5.5, food_desc = 'Rich and creamy dessert with a velvety texture.' WHERE food_name = 'Cheesecake' AND food_category = 'pies-cakes';
UPDATE food SET food_price = 5.0, food_desc = 'Sweet cherry filling in a flaky pastry crust.' WHERE food_name = 'Cherry Pie' AND food_category = 'pies-cakes';
UPDATE food SET food_price = 5.0, food_desc = 'Tender pastry filled with sweet apple filling.' WHERE food_name = 'Apple Pie' AND food_category = 'pies-cakes';
UPDATE food SET food_price = 5.0, food_desc = 'Sweet and tangy blueberries in a flaky pastry crust.' WHERE food_name = 'Blueberry Pie' AND food_category = 'pies-cakes';
UPDATE food SET food_price = 5.5, food_desc = 'Moist and rich dessert with layers of sweetness.' WHERE food_name = 'Layer Cake' AND food_category = 'pies-cakes';
UPDATE food SET food_price = 11.75, food_desc = 'Rich vanilla ice cream paired with a slice of warm pie.' WHERE food_name = 'Pie a la Mode' AND food_category = 'pies-cakes';
UPDATE food SET food_price = 5.25, food_desc = 'Tart and sweet lemon filling topped with a fluffy meringue topping.' WHERE food_name = 'Lemon Meringue' AND food_category = 'pies-cakes';

-- ══ Desserts ══
UPDATE food SET food_price = 6.95, food_desc = 'Creamy and rich, a classic dessert treat.' WHERE food_name = 'Milk Shake' AND food_category = 'desserts';
UPDATE food SET food_price = 14.75, food_desc = '3 scoops, walnuts, syrup, whipped cream and sprinkles, topped with a cherry.' WHERE food_name = 'Walnut Delight' AND food_category = 'desserts';
UPDATE food SET food_price = 6.95, food_desc = 'Creamy soda infused with sweet ice cream flavor.' WHERE food_name = 'Ice Cream Soda' AND food_category = 'desserts';
UPDATE food SET food_price = 13.95, food_desc = '3 scoops, syrup, whipped cream, sprinkles and walnuts topped with a cherry on a sliced banana.' WHERE food_name = 'Banana Split' AND food_category = 'desserts';
UPDATE food SET food_price = 4.95, food_desc = 'Creamy and sweet frozen treat.' WHERE food_name = 'Ice Cream' AND food_category = 'desserts';

-- ══ Ice Cream Sodas ══
UPDATE food SET food_price = 6.95, food_desc = 'Creamy soda infused with sweet ice cream flavor.' WHERE food_name = 'Ice Cream Soda' AND food_category = 'ice-cream-sodas';
UPDATE food SET food_price = 6.95, food_desc = 'Creamy blend of milk and flavor.' WHERE food_name = 'Milkshake' AND food_category = 'ice-cream-sodas';

-- ══ Juices and Fruits ══
UPDATE food SET food_price = 3.5, food_desc = 'Freshly squeezed juice from oranges.' WHERE food_name = 'Orange Juice' AND food_category = 'juices-fruits';
UPDATE food SET food_price = 3.5, food_desc = 'Freshly squeezed juice from crisp apples.' WHERE food_name = 'Apple Juice' AND food_category = 'juices-fruits';
UPDATE food SET food_price = 4.75, food_desc = 'Freshly squeezed orange juice.' WHERE food_name = 'Tropicana Orange Juice' AND food_category = 'juices-fruits';
UPDATE food SET food_price = 3.5, food_desc = 'Freshly squeezed juice from ripe pineapples.' WHERE food_name = 'Pineapple Juice' AND food_category = 'juices-fruits';
UPDATE food SET food_price = 4.5, food_desc = 'Fresh grapefruit, a tangy and refreshing choice.' WHERE food_name = 'Grapefruit' AND food_category = 'juices-fruits';
UPDATE food SET food_price = 6.5, food_desc = 'Fresh melon, perfect for a refreshing snack.' WHERE food_name = '1/2 Melon' AND food_category = 'juices-fruits';
UPDATE food SET food_price = 3.5, food_desc = 'Freshly squeezed juice made from cranberries.' WHERE food_name = 'Cranberry Juice' AND food_category = 'juices-fruits';
UPDATE food SET food_price = 3.5, food_desc = 'Freshly squeezed juice from grapefruit.' WHERE food_name = 'Grapefruit Juice' AND food_category = 'juices-fruits';
UPDATE food SET food_price = 3.5, food_desc = 'Freshly squeezed juice made from ripe tomatoes.' WHERE food_name = 'Tomato Juice' AND food_category = 'juices-fruits';
UPDATE food SET food_price = 6.25, food_desc = 'A refreshing mix of seasonal fruits.' WHERE food_name = 'Fresh Fruit Cocktail' AND food_category = 'juices-fruits';

-- ══ Beverages ══
UPDATE food SET food_price = 2.75, food_desc = 'Fizzy and refreshing soda in a can.' WHERE food_name = 'Canned Soda' AND food_category = 'beverages';
UPDATE food SET food_price = 3.5, food_desc = 'Brewed coffee served over ice.' WHERE food_name = 'Iced Coffee' AND food_category = 'beverages';
UPDATE food SET food_price = 2.75, food_desc = 'Rich and smooth, a classic pick-me-up.' WHERE food_name = 'Coffee' AND food_category = 'beverages';
UPDATE food SET food_price = 3.0, food_desc = 'A selection of refreshing Snapple iced tea flavors.' WHERE food_name = 'Assorted Snapple Iced Tea' AND food_category = 'beverages';
UPDATE food SET food_price = 3.5, food_desc = 'Refreshing and thirst-quenching tea served over ice.' WHERE food_name = 'Iced Tea' AND food_category = 'beverages';
UPDATE food SET food_price = 3.0, food_desc = 'Rich and creamy beverage to warm your day.' WHERE food_name = 'Hot Chocolate' AND food_category = 'beverages';
UPDATE food SET food_price = 2.0, food_desc = 'Refreshing and hydrating water.' WHERE food_name = 'Bottled Water' AND food_category = 'beverages';
UPDATE food SET food_price = 2.75, food_desc = 'A soothing, decaffeinated tea for a relaxing moment.' WHERE food_name = 'Decaf Tea' AND food_category = 'beverages';
UPDATE food SET food_price = 3.0, food_desc = 'A soothing blend of herbal teas, perfect for relaxation.' WHERE food_name = 'Assorted Herbal Tea' AND food_category = 'beverages';
UPDATE food SET food_price = 3.75, food_desc = 'Fresh dairy milk.' WHERE food_name = 'Milk' AND food_category = 'beverages';
UPDATE food SET food_price = 5.0, food_desc = 'Refreshing lime drink with a tangy twist.' WHERE food_name = 'Lime Rickey' AND food_category = 'beverages';
UPDATE food SET food_price = 3.5, food_desc = 'Refreshing coffee without the caffeine kick.' WHERE food_name = 'Iced Decaf Coffee' AND food_category = 'beverages';
UPDATE food SET food_price = 2.75, food_desc = 'Rich and smooth decaffeinated coffee.' WHERE food_name = 'Decaf Coffee' AND food_category = 'beverages';
UPDATE food SET food_price = 5.0, food_desc = 'A classic New York City favorite, a creamy and refreshing drink.' WHERE food_name = 'Egg Cream' AND food_category = 'beverages';

-- Total: 375 items across 42 sections
SELECT CONCAT('Updated: ', ROW_COUNT(), ' rows') AS result;